relativeURLs = false
canonifyURLs = false

baseURL = "/"
languageCode = "en-us"
title = ""
theme = "papermod"

paginate = 0
enableRobotsTXT = true
buildDrafts = true

[params]
  defaultTheme = "light"
  disableThemeToggle = true
  showReadingTime = false
  showShareButtons = false
  showPostNavLinks = false
  showBreadCrumbs = false
  showCodeCopyButtons = true
  showRssButtonInSectionTermList = false
  showToc = false          # we manage TOC manually on the home page
  mainSections = ["none"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  
